-- Snapshot of the kin SQLite schema at SCHEMA_VERSION='1' (end of Phase 3).
-- Used by tests/test_db.py to verify the v1 → v2 migration path against the
-- *actual* prior schema, not the current schema minus a DROP TABLE.
--
-- Do NOT edit this file when the schema evolves. Snapshot the new version
-- at tests/fixtures/schema_v<N>.sql when you bump SCHEMA_VERSION.

CREATE TABLE IF NOT EXISTS _meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS emails (
  id INTEGER PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'jerome',
  folder TEXT NOT NULL DEFAULT 'INBOX',
  message_id TEXT NOT NULL CHECK (message_id != ''),
  uid TEXT,
  from_addr TEXT NOT NULL,
  subject TEXT NOT NULL,
  date TEXT NOT NULL,
  text_body TEXT NOT NULL,
  truncated INTEGER NOT NULL CHECK (truncated IN (0,1)),
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  UNIQUE (user_id, message_id)
);
CREATE INDEX IF NOT EXISTS idx_emails_user_date ON emails (user_id, date DESC);

CREATE TABLE IF NOT EXISTS runs (
  id INTEGER PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'jerome',
  started_at TEXT NOT NULL,
  ended_at TEXT,
  hours INTEGER,
  limit_n INTEGER,
  model TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  args TEXT NOT NULL,
  fetched INTEGER DEFAULT 0,
  filtered INTEGER DEFAULT 0,
  classified INTEGER DEFAULT 0,
  reused INTEGER DEFAULT 0,
  errors INTEGER DEFAULT 0,
  truncated INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_runs_user_started ON runs (user_id, started_at DESC);

CREATE TABLE IF NOT EXISTS classifications (
  id INTEGER PRIMARY KEY,
  email_id INTEGER NOT NULL REFERENCES emails (id) ON DELETE CASCADE,
  run_id INTEGER REFERENCES runs (id),
  model TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  category TEXT,
  priority TEXT,
  action_required INTEGER CHECK (action_required IN (0,1)),
  summary TEXT,
  action_items TEXT,
  dates TEXT,
  confidence REAL,
  truncated INTEGER NOT NULL CHECK (truncated IN (0,1)),
  error TEXT,
  classified_at TEXT NOT NULL,
  CHECK ((error IS NULL) != (category IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_class_unique_success
  ON classifications (email_id, model, prompt_version)
  WHERE error IS NULL;
CREATE INDEX IF NOT EXISTS idx_class_email ON classifications (email_id);
CREATE INDEX IF NOT EXISTS idx_class_classified_at ON classifications (classified_at DESC);
